In [1]:
### Numpy

# It is a library for scientific computing in python. It provides support for arrays and matrices.

In [2]:
!pip install numpy


[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

# create a numpy array

# 1D array
arr1 = np.array([1,2,3,4,5])

print(type(arr1))
print(arr1.shape)

# 2D array
arr2 = np.array([[1,2,4,5,6], [6,7,8,9,2]])
print(arr2.shape)


<class 'numpy.ndarray'>
(5,)
(2, 5)


In [6]:
# in-built functions in numpy

arr = np.arange(1, 12, 2).reshape(3,2)
print(arr)

zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((4,5))
print(ones)

# identity matrix
iden = np.eye(5)
print(iden.dtype)

[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


In [10]:
### Numpy Vectorized Operations

arr1 = np.array([2,3,4,5,6])
arr2 = np.array([1,2,3,4,5])

arr3 = arr1 + arr2

print(arr3)
print(type(arr3))

[ 3  5  7  9 11]
<class 'numpy.ndarray'>


In [11]:
### Universal Functions

arr = np.array([1,2,3,4,5])

print(np.sqrt(arr))
print(np.exp(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [27]:
### Array slicing and indexing

arr = np.array([[1,2,3], [3,4,5], [5,6,7]])
print(arr)

print(arr[1:,1:])


[[1 2 3]
 [3 4 5]
 [5 6 7]]
[[4 5]
 [6 7]]


In [32]:
### Modify array elements

arr[1:] = 100
print(arr)

[[  1   2   3]
 [100 100 100]
 [100 100 100]]


In [39]:
### logical operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data[(data > 5) & (data < 8)])

[6 7]
